---
name: Haskell CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        ghc:
        - '8.2.2'
        - '8.4.4'
        - '8.6.5'
        - '8.8.3'
        - '8.10.1'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1.1
      with:
        ghc-version: ${{ matrix.ghc }}
    - name: Build
      run: |
        ls -l /opt/ghc/
        export PATH=/opt/ghc/bin:$PATH
        cabal --version
        ghc --version
        cabal update
        cabal v2-test -w ghc-${{ matrix.ghc }}
